"""HeyBloopie Minimal Provider Module.

This is a temporary minimal implementation providing `generate_plan` via the
google-genai SDK. It will be replaced by the full Provider Abstraction
Layer in Prompt 9.
"""

import os
from google import genai


async def generate_plan(prompt: str) -> str:
    """Calls Gemini with the prompt and returns the text response.

    Args:
        prompt: Structured prompt string for plan generation.

    Returns:
        The text response generated by Gemini.
    """
    api_key = os.environ.get("GEMINI_API_KEY", "")
    client = genai.Client(api_key=api_key)
    response = await client.aio.models.generate_content(
        model="gemini-1.5-flash",
        contents=prompt,
    )
    return response.text or ""
